// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef CPNET_INSTANCE_HXX
#define CPNET_INSTANCE_HXX

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< char, type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< char, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< char, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< char, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< char, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  typedef ::xsd::cxx::tree::content_order content_order;
  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::bounds< char > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::auto_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
class pref_var_t;
class pref_st_t;
class cpn_t;

#include <memory>    // ::std::auto_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

class pref_var_t: public ::xml_schema::type
{
  public:
  // VARIABLE-NAME
  //
  typedef ::xml_schema::string VARIABLE_NAME_type;
  typedef ::xsd::cxx::tree::traits< VARIABLE_NAME_type, char > VARIABLE_NAME_traits;

  const VARIABLE_NAME_type&
  VARIABLE_NAME () const;

  VARIABLE_NAME_type&
  VARIABLE_NAME ();

  void
  VARIABLE_NAME (const VARIABLE_NAME_type& x);

  void
  VARIABLE_NAME (::std::auto_ptr< VARIABLE_NAME_type > p);

  // DOMAIN-VALUE
  //
  typedef ::xml_schema::short_ DOMAIN_VALUE_type;
  typedef ::xsd::cxx::tree::sequence< DOMAIN_VALUE_type > DOMAIN_VALUE_sequence;
  typedef DOMAIN_VALUE_sequence::iterator DOMAIN_VALUE_iterator;
  typedef DOMAIN_VALUE_sequence::const_iterator DOMAIN_VALUE_const_iterator;
  typedef ::xsd::cxx::tree::traits< DOMAIN_VALUE_type, char > DOMAIN_VALUE_traits;

  const DOMAIN_VALUE_sequence&
  DOMAIN_VALUE () const;

  DOMAIN_VALUE_sequence&
  DOMAIN_VALUE ();

  void
  DOMAIN_VALUE (const DOMAIN_VALUE_sequence& s);

  // Constructors.
  //
  pref_var_t (const VARIABLE_NAME_type&);

  pref_var_t (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  pref_var_t (const pref_var_t& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  virtual pref_var_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  pref_var_t&
  operator= (const pref_var_t& x);

  virtual 
  ~pref_var_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< VARIABLE_NAME_type > VARIABLE_NAME_;
  DOMAIN_VALUE_sequence DOMAIN_VALUE_;
};

class pref_st_t: public ::xml_schema::type
{
  public:
  // STATEMENT-ID
  //
  typedef ::xml_schema::string STATEMENT_ID_type;
  typedef ::xsd::cxx::tree::traits< STATEMENT_ID_type, char > STATEMENT_ID_traits;

  const STATEMENT_ID_type&
  STATEMENT_ID () const;

  STATEMENT_ID_type&
  STATEMENT_ID ();

  void
  STATEMENT_ID (const STATEMENT_ID_type& x);

  void
  STATEMENT_ID (::std::auto_ptr< STATEMENT_ID_type > p);

  // PREFERENCE-VARIABLE
  //
  typedef ::xml_schema::string PREFERENCE_VARIABLE_type;
  typedef ::xsd::cxx::tree::traits< PREFERENCE_VARIABLE_type, char > PREFERENCE_VARIABLE_traits;

  const PREFERENCE_VARIABLE_type&
  PREFERENCE_VARIABLE () const;

  PREFERENCE_VARIABLE_type&
  PREFERENCE_VARIABLE ();

  void
  PREFERENCE_VARIABLE (const PREFERENCE_VARIABLE_type& x);

  void
  PREFERENCE_VARIABLE (::std::auto_ptr< PREFERENCE_VARIABLE_type > p);

  // CONDITION
  //
  typedef ::xml_schema::string CONDITION_type;
  typedef ::xsd::cxx::tree::sequence< CONDITION_type > CONDITION_sequence;
  typedef CONDITION_sequence::iterator CONDITION_iterator;
  typedef CONDITION_sequence::const_iterator CONDITION_const_iterator;
  typedef ::xsd::cxx::tree::traits< CONDITION_type, char > CONDITION_traits;

  const CONDITION_sequence&
  CONDITION () const;

  CONDITION_sequence&
  CONDITION ();

  void
  CONDITION (const CONDITION_sequence& s);

  // PREFERENCE
  //
  typedef ::xml_schema::string PREFERENCE_type;
  typedef ::xsd::cxx::tree::sequence< PREFERENCE_type > PREFERENCE_sequence;
  typedef PREFERENCE_sequence::iterator PREFERENCE_iterator;
  typedef PREFERENCE_sequence::const_iterator PREFERENCE_const_iterator;
  typedef ::xsd::cxx::tree::traits< PREFERENCE_type, char > PREFERENCE_traits;

  const PREFERENCE_sequence&
  PREFERENCE () const;

  PREFERENCE_sequence&
  PREFERENCE ();

  void
  PREFERENCE (const PREFERENCE_sequence& s);

  // Constructors.
  //
  pref_st_t (const STATEMENT_ID_type&,
             const PREFERENCE_VARIABLE_type&);

  pref_st_t (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f = 0,
             ::xml_schema::container* c = 0);

  pref_st_t (const pref_st_t& x,
             ::xml_schema::flags f = 0,
             ::xml_schema::container* c = 0);

  virtual pref_st_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  pref_st_t&
  operator= (const pref_st_t& x);

  virtual 
  ~pref_st_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< STATEMENT_ID_type > STATEMENT_ID_;
  ::xsd::cxx::tree::one< PREFERENCE_VARIABLE_type > PREFERENCE_VARIABLE_;
  CONDITION_sequence CONDITION_;
  PREFERENCE_sequence PREFERENCE_;
};

class cpn_t: public ::xml_schema::type
{
  public:
  // PREFERENCE-VARIABLE
  //
  typedef ::pref_var_t PREFERENCE_VARIABLE_type;
  typedef ::xsd::cxx::tree::sequence< PREFERENCE_VARIABLE_type > PREFERENCE_VARIABLE_sequence;
  typedef PREFERENCE_VARIABLE_sequence::iterator PREFERENCE_VARIABLE_iterator;
  typedef PREFERENCE_VARIABLE_sequence::const_iterator PREFERENCE_VARIABLE_const_iterator;
  typedef ::xsd::cxx::tree::traits< PREFERENCE_VARIABLE_type, char > PREFERENCE_VARIABLE_traits;

  const PREFERENCE_VARIABLE_sequence&
  PREFERENCE_VARIABLE () const;

  PREFERENCE_VARIABLE_sequence&
  PREFERENCE_VARIABLE ();

  void
  PREFERENCE_VARIABLE (const PREFERENCE_VARIABLE_sequence& s);

  // PREFERENCE-STATEMENT
  //
  typedef ::pref_st_t PREFERENCE_STATEMENT_type;
  typedef ::xsd::cxx::tree::sequence< PREFERENCE_STATEMENT_type > PREFERENCE_STATEMENT_sequence;
  typedef PREFERENCE_STATEMENT_sequence::iterator PREFERENCE_STATEMENT_iterator;
  typedef PREFERENCE_STATEMENT_sequence::const_iterator PREFERENCE_STATEMENT_const_iterator;
  typedef ::xsd::cxx::tree::traits< PREFERENCE_STATEMENT_type, char > PREFERENCE_STATEMENT_traits;

  const PREFERENCE_STATEMENT_sequence&
  PREFERENCE_STATEMENT () const;

  PREFERENCE_STATEMENT_sequence&
  PREFERENCE_STATEMENT ();

  void
  PREFERENCE_STATEMENT (const PREFERENCE_STATEMENT_sequence& s);

  // Constructors.
  //
  cpn_t ();

  cpn_t (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f = 0,
         ::xml_schema::container* c = 0);

  cpn_t (const cpn_t& x,
         ::xml_schema::flags f = 0,
         ::xml_schema::container* c = 0);

  virtual cpn_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  cpn_t&
  operator= (const cpn_t& x);

  virtual 
  ~cpn_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  PREFERENCE_VARIABLE_sequence PREFERENCE_VARIABLE_;
  PREFERENCE_STATEMENT_sequence PREFERENCE_STATEMENT_;
};

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

// Parse a URI or a local file.
//

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (const ::std::string& uri,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (const ::std::string& uri,
                          ::xml_schema::error_handler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (const ::std::string& uri,
                          ::xercesc::DOMErrorHandler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse std::istream.
//

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::std::istream& is,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::std::istream& is,
                          ::xml_schema::error_handler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::std::istream& is,
                          ::xercesc::DOMErrorHandler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::std::istream& is,
                          const ::std::string& id,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::std::istream& is,
                          const ::std::string& id,
                          ::xml_schema::error_handler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::std::istream& is,
                          const ::std::string& id,
                          ::xercesc::DOMErrorHandler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse xercesc::InputSource.
//

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::xercesc::InputSource& is,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::xercesc::InputSource& is,
                          ::xml_schema::error_handler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::xercesc::InputSource& is,
                          ::xercesc::DOMErrorHandler& eh,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse xercesc::DOMDocument.
//

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (const ::xercesc::DOMDocument& d,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::cpn_t >
PREFERENCE_SPECIFICATION (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d,
                          ::xml_schema::flags f = 0,
                          const ::xml_schema::properties& p = ::xml_schema::properties ());

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CPNET_INSTANCE_HXX
